[analysis]
lookup_username = "BorisMcSpider"
include_opponent_data = false
analysis_period_months = 12

# Deepest opening in lichess database is 36 moves
opening_search_depth = 36
opening_database_path = "resources/openings.tsv"

[api]
your_email="32023524+jonathanfox5@users.noreply.github.com"
your_username="BorisMcSpider"

[debug]
write_json = true
write_dataframes = true

[stockfish]
threads=16
memory=4096
path="C:\\Users\\jf\\Apps\\Builds\\Stockfish-sf_17.1\\stockfish.exe"
analysis_depth=20
