[analysis]
lookup_username = "BorisMcSpider"
include_opponent_data = false
analysis_period_months = 999

[api]
your_email="32023524+jonathanfox5@users.noreply.github.com"
your_username="BorisMcSpider"
