[analysis]
lookup_username = "BorisMcSpider"
include_opponent_data = false
analysis_period_months = 12

# Deepest opening in lichess database is 36 moves
opening_search_depth = 36
opening_database_path = "resources/lichess_eco.tsv"

[api]
your_email="32023524+jonathanfox5@users.noreply.github.com"
your_username="BorisMcSpider"

[debug]
write_json = true
write_dataframes = true